# Generated by Django 4.2.28 on 2026-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('sports', 'Sports / Stadium'), ('bus', 'Bus'), ('train', 'Train')], default='event', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='seat_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
