# Generated by Django 4.2.28 on 2026-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_category_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='destination',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('sports', 'Sports'), ('bus', 'Bus'), ('train', 'Train')], default='event', max_length=20),
        ),
    ]
